fix: concurrent update error for CPU & mem target
Without this change, terraform may attempt to create both the CPU
and Memory scaling targets at the same time, leading to errors like the
following:

Error: creating Application AutoScaling Target (service...): operation
error Application Auto Scaling: RegisterScalableTarget, https response
error StatusCode: 400, ... ConcurrentUpdateException: You already have
a pending update to an Auto Scaling resource.